version: '3'

services:
  node:
    build: .
    container_name: inventory-server
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    networks:
      - inventory-network
    expose:
      - 8080

networks:
  inventory-network:
    