  version: '3'

  services:
    node:
      build: .
      container_name: inventory-server      
      environment:
        - NODE_ENV=production        
      depends_on:
        - db
      networks:
        - inventory-network      
      ports:
        - "8888:8888"

    db:
      image: mysql:latest      
      container_name: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"
      volumes:
        - ./database:/var/lib/mysql
      networks:
        - inventory-network

    adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
      networks:
        - inventory-network

  networks:
    inventory-network:
